### ISSUE TITLE
CTHUB -  Research Metabase Security Model

### ISSUE THREAD

**Issue by shayjeff** [bcgov/cthub#144]
**Problem Description** Right now everyone is an Admin in Metabase. We need to determine security architecture.
**In order to** protect data and establish roles for varying levels of access and functionality.

**Solution Needs**
- Admin role: only dev's should have admin access, database tables should be restricted only models will be accessible.
- Business admin role: for managing users (admin without data base access). 
- Analyst/Engineering role: for creating SQL questions based on models.
- Dashboard role: for creating dashboards ( or is this the same as creating SQL questions?).
- Viewer role: internal, internal government/IDIR users
- Viewer role: external public 

Security Groups
- Ability to group models into different security access (Moti, CAS, TB)

**Timebox**
- Half a day to a day

**Outcome**
Details describing the outcome of the research 
- Testing each role individually should allow for only the functionality listed above.

**Additional Context**
- enter text here
- enter text here

**Comment by kcabhar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/144?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745

**Comment by JulianForeman** [comment]
Working from top down of the roles:

Business Admin/Admin Role: The only way I have been seeing on Metabase documentation on questions online is that you have to be admin in order to invite people to the database.  There are options on some paid plans that allow for something called a "group manager" which can add or remove people from groups however they still cannot invite new people to the database in the first place. So someone on the business side will have to have admin in order for people to join metabase unless this is being left up to the devs.

*Update*
There is mentioning that on some paid plans there is an option to grant users specific application permissions like potentially editing users/groups without making them an Administrator.

Analyst/Engineering: This one is pretty straight forward, if we just create groups for each database called something like "Zeva Analyst/Engineer" we can give unrestricted access to the whole database but not native query editing. From what I saw that means people can create questions and such but won't be able to directly interact with the database, this can also be restricted down to the tables so there's lots of room for customization here.

Dashboard role: Permissions documentation seems to mention that sql questions and dashboards can be separated into different group permissions. So if we want a dashboard role that is different than one that can create questions it's possible.

Viewer roles: To put it very simply, we can turn off all editing capabilities for these types of roles and restrict them to only be able to view questions/dashboards.
