### ISSUE TITLE
CTHUB - ARC File Upload

### ISSUE THREAD

**Issue by shayjeff** [bcgov/cthub#294]
**Describe the task**
Add the ARC data file to CTHUB.

Location:Teams Files/CTHUB/Data_2024/ARC
FIle: ARCDataTracking_2024-06-26.xlsm
- `ARC Data` sheet contains the dataset
- `Data_Tab_Format` provides information about field formats, errors and other metadata details.

**Purpose**
The purpose of this task is to enable the business area the ability to uploading ARC data by into CTHUB.

**Acceptance Criteria**
- [x] Add ARC to upload dropdown so that it appears in Metabase.
- [x] User should get error if cell value is not in the "Values" list.
- [x] User should get get an error if values are missing in a column where missing values are not allowed.
- [x] User should get an error if the value is not numeric or not datetime.

Development Checklist:
- [ ] New tables to contain ARC data and region data (joined)
- [x] Create service for upload
- [ ] Keep in mind the region field will come in as a string but will need to be split up if it contains more than one, joined to the region table (get_or_create)

**Additional context**
- Economic Region: Not sure how `Across BC` value would work. What if one person selects all economic regions of BC and another person chooses `Across BC`. **- added a comment about this**

**Comment by katerinkus** [comment]
@shayjeff I have added details about ARC to the card and it is ready to go.

**Comment by katerinkus** [comment]
@JulianForeman The `Economic Region` field allows multiple values (e.g. _Thompson-Okanagan_, _Nechako_, _Vancouver Island & Coast_) in a single cell from the list of all [economic regions](https://www.welcomebc.ca/choose-b-c/explore-british-columbia/regions-in-b-c).

In addition to that, they also have the _Across BC_ option which appears redundant because you could select all of the regions instead. However, I was asked to keep this category in cases where it is not very clear where the project is taking place.

Eventually, we will have a map with all of the economic regions. Since _Across BC_ is not a region, it would need to be converted into a list containing all of the regions (_Vancouver Island/Coast_, _Mainland/Southwest_, _Thompson-Okanagan_, _Kootenay_, _Cariboo_, _North Coast_, _Nechako_, _Northeast_) so that all regions would be displayed on the map. Perhaps, an additional field would need to be created so that `Across BC` is displayed in the dashboard dropdown but another field with all of the regions is shown on the map.

**Comment by katerinkus** [comment]
I've added location of the file to the ticket.

**Comment by katerinkus** [comment]
Currently, waiting on the economic region table to be updated to stop "Column: Economic Region
Error Name: Invalid Region" error from happening.

**Comment by katerinkus** [comment]
Here is the [card](https://github.com/orgs/bcgov/projects/182/views/1?pane=issue&itemId=75396877) to address the Economic Region issue. Unfortunately, without addressing this issue I cannot see if the ARC file has uploaded.

**Comment by katerinkus** [comment]
Uploaded it on dev with success! Thank you, Julian 🙂!
