### ISSUE TITLE
CTHUB -  Convert GER Columns to Expected Types

### ISSUE THREAD

**Issue by shayjeff** [bcgov/cthub#298]
**Describe the task**
Convert the GER columns to their expected types.

**Purpose**
This will allow the data to be consistently handled as strings and preventing unexpected errors or inconsistencies in data processing and analysis.

**Acceptance Criteria**
- [ ] Update all relevant fields for GER in the code and database.

**Additional context**

**Comment by katerinkus** [comment]
I wanted to comment on the Purpose to may it clearer. The purpose is to change the 'Approvals', 'Applicant Name', 'Category', 'Fleet/Individuals',  'Rebate adjustment (discount)', 'Manufacturer', 'City', 'Model', 'Postal code', 'VIN Number', 'Email', 'Phone' to strings so that can be stripped of trailing whitespaces and capitalized like this according to the notes in Request 1.1.

**Comment by ArawuSamuel1** [comment]
Thank you @JulianForeman 
Amazing work

**Comment by shayjeff** [comment]
This card will be broken down into sections. New cards will be created.
