### ISSUE TITLE
CTHUB - List of geographic locations

### ISSUE THREAD

**Issue by katerinkus** [bcgov/cthub#322]
**Describe the task**
GER dataset and likely other datasets contain community names. In order to find typos, the easiest way is to first obtain a list of all communities in BC. The goal of this task is to research where to obtain a list that is updated regularly by Stats Canada or BC Government that we can access via API.

**Purpose**
To find typos in geographic name spellings.

**Timebox**
1 day 

**Acceptance Criteria**
- [ ] A list of BC communities that are incorporated (e.g. Vancouver) or [designated places](https://en.wikipedia.org/wiki/List_of_designated_places_in_British_Columbia).
- [x] Access via API or download (if API options are not available)

**Additional context**
A full list can be found here: [Stats Canada](https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=9810000401&pickMembers%5B0%5D=1.5940&geocode=). BC also has BC Geographical Names portal [here](https://apps.gov.bc.ca/pub/bcgnws/web/). They are both problematic because the former is a CSV download and the latter does not appear to have an API. But if we do not find anything better, we can use the former.

**Comment by ArawuSamuel1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Team-Zelda-637d5bc12e6201001055b745/issues/bcgov/cthub/322?planning-poker) with Zenhub @emi-hi @JulianForeman @tim738745

**Comment by katerinkus** [comment]
@emi-hi Sounds great! Many thanks for finding it. Would it be possible to update the data in our system every year or so?

**Comment by tim738745** [comment]
@katerinkus @emi-hi Just to add to what Emily wrote, we thought that to check a community name, we would have to make a request to the API with the name and with the "exactSpelling" flag set to true, and so that means we would have to query the API once for each record in an uploaded spreadsheet. This is less scalable than using a downloaded data set, which is why we were leaning towards using a download.

But I realized another way of doing the checks would be to :
(1) send the API a string of community names (with exactSpelling set to false), and it does return a list of features that match the names according to its own internal matching logic.
(2) Iterate through our community names and see which ones are in the list (meaning no typo), and which ones are not (meaning typo)

Then we would only have to do one query per upload, and we wouldn't have to maintain our own dataset of geographic locations.

Sorry for changing my mind, but now I'm leaning more towards using the API!

**Comment by tim738745** [comment]
@emi-hi I think you can use the featureType parameter of the API (featureType=1 means city, =2 means community; see the /featureTypes endpoint). So we can do 2 search queries, one for cities and the other with communities, each with the same search string.

Alternatively, we can do featureType=* (the default), and we can process the query result on our end to exclude any of the features that's not of the type we want.

**Comment by shayjeff** [comment]
Reviewed
